Refactoring c# projects
emilybache/GildedRose-Refactoring-Kata pull request #544
Opened 2024-05-31 06:38 UTC by StefH

- [x] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.

## Please provide your PR description below this line
- Use file-scoped namespaces everywhere
- Changed csproj files : added RootNamespace
- Removed NUnit/GildedRoseTests/TextTestFixture.cs because the same logic is defined in csharp.NUnit/GildedRose/Program.cs
- Program.cs is the same for both (⭐: actually I think it's even better to only have 1 main GildedRose project which is defined in the NUnit project and referenced in the other xUnit project)
- small changes from `GildedRose(IList<Item> Items)` to `GildedRose(IList<Item> items)` and `IList<Item> Items;` to `private readonly IList<Item> _items;` to be more conformant with C# .NET coding guidelines.

2024-06-02 07:22 UTC, codecop requested changes
Added some in line comments. Also please keep formatting changes minimal if possible (unless missing formatting). Thank you

2024-06-02 07:22 UTC, codecop commented on csharp.NUnit/GildedRose/Program.cs
> +        for (var i = 0; i < 31; i++)
We need dynamic days as all other texttest fixture files have them. Please keep that

2024-06-02 07:22 UTC, codecop commented on csharp.xUnit/GildedRose/GildedRose.cs
> +    private readonly IList<Item> _items;
Items are package access and mutable in other languages. Please do not change this. Also keep original name please

2024-06-02 07:22 UTC, codecop commented on csharp.NUnit/GildedRose/Program.cs
> +
Why?

2024-06-02 07:22 UTC, codecop commented on csharp.xUnit/GildedRose/Program.cs
> +        for (var i = 0; i < 31; i++)
Should be dynamic like other one

2024-06-02 07:23 UTC, codecop commented on csharp.xUnit/GildedRose/GildedRose.cs
> +    private readonly IList<Item> _items;
This is already part of exercise

2024-06-02 09:13 UTC, StefH commented on csharp.NUnit/GildedRose/Program.cs
> +        for (var i = 0; i < 31; i++)
Original xUnit test did also not have this. But I'll add this back.

2024-06-02 09:21 UTC, StefH commented
@codecop 
Please check the files again if it's ok.

2024-06-02 18:09 UTC, codecop commented
Thank you. Now I see, the original code was already inconsistent. That is a pity. So as background for you, the code should look the same as much as possible for both projects. From what I see here I think project files, GildedRose and Item are identical. Both `Program` are almost identical besides the missing dynamic `days` in the second one. While it has not been there if you can please add it to improve the consistency between the versions. Also both Approvaltests should look as similar as possible. Because you have the project open, maybe you can run a diff between both folders to verify my assumption. If all is good, then please squash your changes to one commit. We are nearly there ;-) Thank you for your patience.

2024-06-02 19:47 UTC, StefH commented
@codecop 
- I've fixed the dynamic `days` and the two main projects are now identical. So only 1 main GildedRose project is needed. I can make that change in this PR also if you approve.
- Both Approvaltests look as similar as possible
- I did a diff between the 2 folders
- squash your changes to one commit --> Normally I don't do this, I do this when I merge the PR to master, in that case I use Squash commit, this makes the Git Timeline even cleaner.

My project
![image](https://github.com/emilybache/GildedRose-Refactoring-Kata/assets/249938/29230db6-953f-4f36-990c-1920cf932010)

This project
![image](https://github.com/emilybache/GildedRose-Refactoring-Kata/assets/249938/9d012880-035f-4be7-89fd-e5d5f79244a2)

2024-06-02 19:49 UTC, StefH commented
@codecop 
Now I just see that you have already merged my PR?

2024-06-06 08:58 UTC, emilybache commented
Hi, thanks to both of you for doing this, I'm happy to see these changes. I think I will ask @codecop to take another look and do the merge as he sees fit.

2024-06-06 12:13 UTC, merged